# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: GraphQL Gateway Maven Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build with Maven
        if: ${{ github.ref != 'refs/heads/master' }}
        run: mvn -B package --file pom.xml
        
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
     
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          token: ${{ secrets.REPO_GIT_TOKEN }}
          

      - name: Publish Snapshot to OSS Maven Repository
        if: ${{ github.ref == 'refs/heads/master' }}
        run: mvn -B --batch-mode deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
