name: 'Test Report'

on:
  workflow_run:
    workflows: [CI]                     
    types: [completed]

jobs:
  report: 
    runs-on: ubuntu-latest  
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Maven Tests
          path: "*.xml"
          reporter: java-junit
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}
